services:
  docs:
    image: online_learning_platform_local_docs
    container_name: online_learning_platform_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./online_learning_platform:/app/online_learning_platform:z
    ports:
      - '9000:9000'
    command: /start-docs
